services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: pingpal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: